### ISSUE TITLE
Port v0 RANSAC

### ISSUE THREAD

**Issue by wggster** [DylanLukes/renkon#7]
depends on #1 and #2

**Comment by wggster** [comment]
- [ ] Research instability of statistical inference due to depending on statsmodels/scipy (e.g., find core algorithm)
- [ ] Copy over basic RANSAC scaffold
- [ ] Address all the TODO items that are in the old code
- [ ] Fix instability (e.g., copy core code/algorithm)

**Comment by DylanLukes** [comment]
Working on this, with `Linear`, `Normal`, and `Uniform` as exemplars. Working in conjunction with implementing simple batch interface for testing. Then, next steps are #9/10.

**Comment by DylanLukes** [comment]
- [ ] Port notebook RANSAC into mainline code.

**Comment by DylanLukes** [comment]
- [ ] Resolve buggy inconsistencies when running in tests.
